# Application YAML configuration

# Set port to 8080
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:rexa}
    username: ${POSTGRES_USER:rexaAdmin}
    password: ${POSTGRES_PASSWORD:rexaAdmin}
  application:
    name: rexa
  jooq:
    sql-dialect: Postgres

xnat:
  url: http://localhost
  user: admin
  password: admin
