# Application YAML configuration

# Set port to 8080
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5442/${POSTGRES_DB:rexa}
    username: ${POSTGRES_USER:rexaAdmin}
    password: ${POSTGRES_PASSWORD:rexaAdmin}
  application:
    name: rexa
  jooq:
    sql-dialect: Postgres
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 95069339481-snr5vq6toevl0objs0e360uibop8jgg4.apps.googleusercontent.com
            clientSecret: _iqhRL9lti3EwfBwas_BmAdG
            scope:
              - email
              - profile
l
app:
  oauth2:
    authorizedRedirectUris: http://localhost:8080/oauth2/redirect
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 86400000

xnat:
  secret: xnat-decrypt-secret

