# Application YAML configuration

# Set port to 8080
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rexa
    username: 'rexaAdmin'
    password: 'rexaAdmin'
  application:
    name: rexa
  jooq:
    sql-dialect: Postgres

xnat:
  url: http://localhost
  user: admin
  password: admin
