version: '3.6'

services:
  rexa-db:
    container_name: rexa-db
    image: postgres:12.2
    ports:
      - 5442:5432
    restart: always
    environment:
      POSTGRES_USER: rexaAdmin
      POSTGRES_PASSWORD: rexaAdmin
      POSTGRES_DB: rexa
    networks:
      - rexa-network

networks:
  rexa-network:
    driver: bridge
