name: Add review done when one approval
on:
  pull_request_review:
    branches-ignore:
      - master
jobs:
  build:
    name: Label when approved

    runs-on: ubuntu-latest

    steps:
    - name: Label approved pull requests
      uses: abinoda/label-when-approved-action@1.0.5
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "Review Done"
